### ISSUE TITLE
Sensor Type

### ISSUE THREAD

**Issue by ljan** [ljan/ESP_mqtt-temphum#4]
Some possible Sensors:

|    | DHT22 | Si7021 |
| :---         |     :---:      |   :---: |
| VCC | 3.3 - 5.2 V | 1.9 - 3.6 V (max 4.2 V) |
| Current Active | 500 µA | 150 µA |
| Current Standby | 15 µA | 60 nA |
| Sampling Period | ~2 s | max 80 ms Power Up <br> max 25 ms Conversion |
| Interface | 1-Wire | 2-Wire (I²C) |

**DHT22** is simple but slow. With wifi taking long to connect this possibly is irrelevant.
**Si7021** way faster to get readings but uses one more pin.

Standby current does not matter as VCC is directly driven by ESP-pin.

**Comment by junandi** [comment]
The Si7021 is also very small and could be directly integrated in the PCB.
If deciding to use a LDO, Si7021 would allow to go with HT7330 or even HT7327 - one could for example provide pads and a jumper or solder bridge to optionally use the LDO.

**Comment by ljan** [comment]
Both Sensor Types now supported
Type can be specified in config.h
